import { CategoryType } from '../stores/episodeStore';

export type UrgencyLevel = 1 | 2 | 3 | 4 | 5;

export const CATEGORY_URGENCY_CONTEXTS: Record<string, Record<UrgencyLevel, string>> = {
  'Medical Emergency': {
    1: 'Requesting basic first-aid advice and non-urgent medical guidance at my location.',
    2: 'Experiencing minor injury or persistent pain; need assistance with basic first-aid supplies.',
    3: 'Requiring prompt medical assistance for sudden illness, high fever, or moderate trauma.',
    4: 'Severe medical condition requiring urgent paramedic intervention and immediate transport.',
    5: 'CRITICAL: Unresponsive individual, severe cardiac distress, or heavy trauma. Immediate life support needed.',
  },
  'Security & Assault': {
    1: 'Reporting suspicious individuals or suspicious activity loitering in the immediate vicinity.',
    2: 'Experiencing uncomfortable confrontation or aggressive verbal disturbance nearby.',
    3: 'Facing active intimidation or hostile presence; need community safety intervention.',
    4: 'Imminent danger from aggressive attackers or violent assault in progress; urgent help needed.',
    5: 'CRITICAL: Life-threatening physical assault or armed threat underway. Immediate emergency defense required.',
  },
  'Fire & Explosion': {
    1: 'Smell of burning or minor smoke odor noticed nearby; requesting preventive check.',
    2: 'Contained small trash or appliance fire with visible smoke; need fire extinguisher assist.',
    3: 'Spreading structural or outdoor fire; need local volunteer containment and rapid response.',
    4: 'Rapidly spreading major fire with heavy smoke; occupants actively evacuating the premises.',
    5: 'CRITICAL: Major structure fire, blast, or trapped victims inside burning building. Immediate rescue needed.',
  },
  'Women Safety & Harassment': {
    1: 'Feeling uneasy in an isolated area; requesting remote check-in or companion guidance.',
    2: 'Encountering persistent unwanted following or verbal harassment in public.',
    3: 'Actively being stalked or cornered; urgent physical presence requested for deterrence.',
    4: 'Severe harassment with physical intimidation; seek urgent refuge and immediate intervention.',
    5: 'CRITICAL: Emergency SOS triggered. Violent physical assault or abduction threat in progress.',
  },
  'Accident & Collision': {
    1: 'Minor vehicle fender bender with no injuries; assistance requested with roadside safety.',
    2: 'Low-impact collision with minor bruising; need assistance with vehicle clearing and first aid.',
    3: 'Road collision with moderate injuries and vehicle damage; need responder first aid and traffic safety.',
    4: 'Severe crash with multiple injured persons and heavy vehicular entrapment; urgent dispatch needed.',
    5: 'CRITICAL: Catastrophic multi-vehicle pileup with critical casualties and trapped passengers.',
  },
  'Transport & Evacuation': {
    1: 'Inquiring about available emergency transit routes or scheduled evacuation points.',
    2: 'Unable to find transport in remote area; require non-critical ride assist to safe zone.',
    3: 'Stranded without transit during adverse conditions; need immediate transport assistance.',
    4: 'Urgent evacuation required due to impending regional hazard or rising danger.',
    5: 'CRITICAL: Immediate emergency extraction required from active hazard zone; lives at risk.',
  },
  'Disaster & Flood': {
    1: 'Monitoring rising water levels or weather warning; requesting sandbags and guidance.',
    2: 'Water entering ground floor or storm debris blocking exits; need physical help securing property.',
    3: 'Rapid floodwaters or storm structural damage; requiring rescue assistance to reach dry ground.',
    4: 'Severe flash flood or building collapse imminent; occupants cut off from exit routes.',
    5: 'CRITICAL: Trapped by rapidly surging floodwaters or catastrophic disaster debris. Zero-delay rescue needed.',
  },
  'Domestic Violence & Abuse': {
    1: 'Seeking confidential safety advice and local shelter contact information.',
    2: 'Facing escalating hostile domestic argument; requesting discreet welfare monitoring.',
    3: 'Active domestic dispute with threatening behavior; need immediate safe intervention.',
    4: 'Physical domestic violence in progress; victim needs immediate safe extraction and shelter.',
    5: 'CRITICAL: Severe life-threatening domestic violence or assault in progress. Extreme emergency response required.',
  },
  'Child Emergency & Lost': {
    1: 'Reporting a child separated in a public area; seeking nearby volunteer lookout assistance.',
    2: 'Unattended toddler or wandering child spotted; need assistance locating guardians.',
    3: 'Child missing for over 15 minutes in crowded or unfamiliar area; immediate search grid needed.',
    4: 'Pediatric acute distress or sudden child medical crisis; urgent responder aid required.',
    5: 'CRITICAL: Missing child in hazardous surroundings or critical infant airway/medical emergency.',
  },
  'Senior Citizen Assist': {
    1: 'Senior citizen requesting routine welfare check-in or non-urgent household assist.',
    2: 'Elderly individual experiencing mobility difficulty or mild disorientation.',
    3: 'Senior citizen suffered a fall, unable to get up unassisted; needs urgent physical help.',
    4: 'Elderly resident experiencing acute confusion, pain, or suspected stroke symptoms.',
    5: 'CRITICAL: Senior citizen unconscious or in severe respiratory/cardiovascular collapse.',
  },
  'Mental Health Crisis': {
    1: 'Feeling elevated anxiety and stress; requesting calm peer de-escalation talk.',
    2: 'Experiencing acute panic attack and disorientation; need quiet grounding support.',
    3: 'Severe emotional distress or behavioral breakdown; requiring compassionate in-person presence.',
    4: 'Acute psychological crisis with potential self-harm risk; urgent professional intervention needed.',
    5: 'CRITICAL: Active suicide attempt or severe self-harm in progress. Immediate crisis rescue needed.',
  },
  'Stranded & Breakdown': {
    1: 'Vehicle running low on fuel or flat tire; requesting non-urgent roadside advice.',
    2: 'Mechanical breakdown or dead battery on safe roadside shoulder; need jump-start or tools.',
    3: 'Vehicle disabled in poorly lit or isolated location; need fast roadside assistance.',
    4: 'Stranded in hazardous terrain or inclement weather with no heating and vulnerable passengers.',
    5: 'CRITICAL: Vehicle disabled in active traffic lane or perilous mountain ledge; extreme risk of collision.',
  },
  'Blood & Organ Need': {
    1: 'Inquiring about blood donor registries for an upcoming scheduled surgery.',
    2: 'Seeking replacement blood units for hospitalized patient within the next 24 hours.',
    3: 'Urgent need for specific blood type / platelets for surgery happening today.',
    4: 'Emergency blood donor call for patient experiencing severe hemorrhagic trauma.',
    5: 'CRITICAL: Rare blood type units urgently required immediately to save a patient in operating room.',
  },
  'Oxygen & Med Supply': {
    1: 'Seeking information on local oxygen refilling stations or pharmacy delivery.',
    2: 'Medication running low for chronic condition; need prescription pickup assist.',
    3: 'Oxygen concentrator running low on reserve; need urgent oxygen cylinder delivery.',
    4: 'Critical shortage of lifesaving medication (insulin, inhaler, anti-venom, cardiac drugs).',
    5: 'CRITICAL: Patient completely depleted of supplemental oxygen; asphyxiation risk within minutes.',
  },
  'Cyber Threat & Stalking': {
    1: 'Seeking advice on suspicious digital communications or phishing attempt.',
    2: 'Experiencing targeted online harassment or account takeover attempts.',
    3: 'Active digital stalking with real-time location tracking threats; need security triage.',
    4: 'Severe cyber blackmail and extortion with imminent real-world physical threat.',
    5: 'CRITICAL: Immediate threat of physical violence coupled with real-time digital device compromise.',
  },
  'Animal Rescue & Hazard': {
    1: 'Reporting stray animal wandering in neighborhood; requesting non-urgent shelter lookup.',
    2: 'Injured small animal or bird found; need transport to local veterinary clinic.',
    3: 'Large injured animal trapped in drain or road; need volunteer rescue equipment.',
    4: 'Aggressive or rabid animal threatening pedestrians in public pathway.',
    5: 'CRITICAL: Venomous snake bite or dangerous predator actively attacking persons.',
  },
  'Power Grid & Blackout': {
    1: 'Reporting minor power fluctuation or single-home fuse outage.',
    2: 'Neighborhood block blackout; requesting status check and emergency lighting.',
    3: 'Prolonged power outage affecting medical refrigeration or temperature control.',
    4: 'Downed live power lines sparking near walkway or residence; high electrocution risk.',
    5: 'CRITICAL: Live high-voltage electrical cable in contact with water/vehicle with trapped individuals.',
  },
  'Gas & Chemical Leak': {
    1: 'Faint smell of gas outdoors; requesting preventive air check.',
    2: 'Domestic LPG cylinder hiss or minor valve leak detected; need isolation assist.',
    3: 'Strong chemical odor or indoor gas accumulation; requiring immediate evacuation assistance.',
    4: 'Ruptured commercial gas pipeline or hazardous chemical spill spreading rapidly.',
    5: 'CRITICAL: Massive toxic gas cloud or impending flammable gas explosion. Immediate area evacuation.',
  },
  'Theft & Burglary': {
    1: 'Reporting past theft of unattended property for documentation.',
    2: 'Signs of attempted tampering on doors, windows, or locks.',
    3: 'Trespasser spotted on private premises; requesting urgent community presence.',
    4: 'Active burglary or break-in in progress; intruder currently inside building.',
    5: 'CRITICAL: Armed robbery or violent home invasion in progress with occupants held captive.',
  },
  'Food & Water Crisis': {
    1: 'Inquiring about local community food pantry and drinking water distribution points.',
    2: 'Short-term supply shortage for isolated household; need basic ration assistance.',
    3: 'Vulnerable group without potable water or food for over 24 hours; need relief delivery.',
    4: 'Severe water contamination or acute food starvation in isolated disaster pocket.',
    5: 'CRITICAL: Mass dehydration and starvation crisis affecting infants and frail elders with zero access.',
  },
  'Shelter & Homeless Relief': {
    1: 'Inquiring about temporary night shelter beds and warming centers.',
    2: 'Displaced individual needing warm blankets and basic hygiene supplies.',
    3: 'Families displaced by eviction or minor hazard needing urgent emergency overnight shelter.',
    4: 'Vulnerable individuals exposed to extreme sub-zero cold or heatwave without shelter.',
    5: 'CRITICAL: Life-threatening exposure to blizzard/extreme weather; immediate survival shelter needed.',
  },
  'General Request': {
    1: 'Seeking general community information, directions, or non-urgent neighborhood guidance.',
    2: 'Minor assistance required for non-emergency task or localized community query.',
    3: 'I need immediate assistance and support from nearby volunteers at my current location.',
    4: 'Urgent distress situation requiring prompt in-person community response and aid.',
    5: 'CRITICAL: Extreme emergency situation requiring immediate, coordinated volunteer response.',
  },

  // 20 Stranger Connection Categories
  'Coffee & Social Chat': {
    1: 'Quick recommendation exchange or text chat for local coffee spots and casual banter.',
    2: 'Virtual pre-meetup chat to discuss shared social interests and weekend availability.',
    3: 'Casual 30-minute public cafe coffee meetup for friendly face-to-face conversation.',
    4: 'Regular weekly coffee & social hangout group with nearby neighborhood peers.',
    5: 'High-trust community host organizing localized social gatherings and welcome meetups.',
  },
  'Study & Homework Buddy': {
    1: 'Sharing study notes, course syllabus questions, or quick online topic clarification.',
    2: 'Virtual study session via voice/video call to review exam material together.',
    3: 'In-person library or quiet coffee shop co-studying and exam preparation session.',
    4: 'Ongoing dedicated study partnership for semester-long academic goal achievement.',
    5: 'Masterclass peer tutoring, pair-programming sprint, or intensive research collaboration.',
  },
  'Sports & Workout Partner': {
    1: 'Asking for nearby gym recommendations, fitness tips, or workout routine advice.',
    2: 'Virtual fitness accountability check-in and sharing workout schedules.',
    3: 'Outdoor jogging, cycling, or casual gym workout session together in a public park/gym.',
    4: 'Recreational team sports match partner or regular workout training duo.',
    5: 'High-intensity marathon training companion or outdoor adventure co-expedition.',
  },
  'Travel & Sightseeing Companion': {
    1: 'Inquiring about local tourist spots, scenic routes, or transit tips in the area.',
    2: 'Planning a city walking itinerary or sharing travel tips over chat.',
    3: 'Afternoon city walking tour, museum visit, or local heritage trip with a peer.',
    4: 'Day-trip companion for hiking, sightseeing, or nearby countryside road trip.',
    5: 'Multi-day backpacking or travel co-expedition with verified local peer traveler.',
  },
  'Language Exchange & Practice': {
    1: 'Short text translation help or vocabulary practice over chat.',
    2: '15-minute voice call for basic conversational language practice.',
    3: 'In-person language coffee exchange (30 mins target language / 30 mins native).',
    4: 'Weekly structured dual-language immersion and accent practice session.',
    5: 'Deep cultural immersion pairing, document translation aid, and native language host buddy.',
  },
  'Skill Swap & Mentorship': {
    1: 'Quick expert tip or feedback on a project snippet over chat.',
    2: 'Structured online video demonstration of a specific skill or technique.',
    3: 'One-on-one hands-on skill exchange session in a public community space.',
    4: 'Recurring mutual mentorship program across complementary creative/technical domains.',
    5: 'Intensive project co-building, startup skill mentorship, or master-apprentice pairing.',
  },
  'Hobby & Gaming Pair': {
    1: 'Casual online game match or sharing gaming handles & hobby tips.',
    2: 'Virtual multiplayer squad gaming session with voice comms.',
    3: 'Public cafe board game meetup, arcade hangout, or tabletop gaming session.',
    4: 'Regular gaming tournament team member or weekly hobby club participant.',
    5: 'High-stakes esports tournament duo or tabletop campaign DM/co-host.',
  },
  'Co-Working & Professional Network': {
    1: 'Inquiring about local co-working spaces, cafes with Wi-Fi, or industry advice.',
    2: 'Virtual career networking or portfolio peer review call.',
    3: 'Co-working focus session at a local cafe or shared workspace side-by-side.',
    4: 'Weekly professional focus sprint & mastermind accountability group.',
    5: 'Technical co-founder pairing, joint venture ideation, or business partnership.',
  },
  'Event & Concert Buddy': {
    1: 'Asking if anyone nearby is attending an upcoming concert, expo, or show.',
    2: 'Coordinating ticket purchases or ride-share planning for an upcoming event.',
    3: 'Meeting up at venue entrance to attend a concert, play, or exhibition together.',
    4: 'Full-day music festival or multi-track conference companion group.',
    5: 'Concert tour trip partner, festival camper co-pilot, or event co-organizer.',
  },
  'Neighborhood Advice & Local Guide': {
    1: 'Asking quick questions about local neighborhood areas, safety, or utilities.',
    2: 'Sharing a customized local neighborhood guide or essential contact list.',
    3: 'Short 20-minute neighborhood orientation walk for a newcomer.',
    4: 'Active relocation companion helping navigate local markets and services.',
    5: 'Comprehensive city welcome ambassador and community orientation host.',
  },
  'Pet Playdate & Walking': {
    1: 'Asking about dog-friendly parks, local vets, or pet supply stores nearby.',
    2: 'Virtual pet photo swap and scheduling a casual park walk.',
    3: 'Joint dog walk in a public dog park or neighborhood trail.',
    4: 'Co-organizing weekly breed playdates or neighborhood pet walking groups.',
    5: 'Trusted peer pet sitting or emergency temporary foster care.',
  },
  'Foodie & Culinary Meetup': {
    1: 'Asking for local food recommendations or dietary-friendly restaurant tips.',
    2: 'Selecting a dining spot and organizing a group table reservation over chat.',
    3: 'Casual lunch or dinner meetup at a local restaurant with a food enthusiast peer.',
    4: 'Group food crawl, night market exploration, or weekend potluck dinner.',
    5: 'Masterclass cooking workshop or community feast co-hosting.',
  },
  'Book & Film Discussion': {
    1: 'Book or movie recommendation request and brief review exchange.',
    2: 'Virtual online book chapter breakdown or film reaction discussion call.',
    3: 'In-person coffee chat to discuss a recently read book or movie in depth.',
    4: 'Regular monthly book club or weekend cinema group outing.',
    5: 'Literary workshop host, indie film screening organizer, or script table-read lead.',
  },
  'Music Jamming & Creative': {
    1: 'Sharing music samples, favorite genres, or instrument gear advice over chat.',
    2: 'Virtual jam session or exchanging audio stems for asynchronous collaboration.',
    3: 'Acoustic park session or public music studio jam with instruments/vocals.',
    4: 'Ongoing band formation or regular rehearsal room practice.',
    5: 'Live gig performance pairing, studio recording, or concert songwriting duo.',
  },
  'Carpool & Commute Partner': {
    1: 'Asking about traffic conditions, metro routes, or typical commute times.',
    2: 'Coordinating route alignment and departure time for a shared ride.',
    3: 'One-off shared commute or cab share to split transportation costs.',
    4: 'Regular weekday daily carpool partner to work or university.',
    5: 'Long-distance highway road trip carpool driver & co-pilot pairing.',
  },
  'Tech & Coding Collaboration': {
    1: 'Asking a technical question, stack recommendation, or quick bug check.',
    2: 'Virtual pair-programming session or GitHub pull request code review.',
    3: 'Cafe hack session to work on personal coding side-projects side-by-side.',
    4: 'Weekend hackathon team formation and rapid MVP prototyping.',
    5: 'Long-term open-source project co-maintainer or technical product co-founder.',
  },
  'Item Sharing & Borrowing': {
    1: 'Inquiring if anyone nearby has a specific tool, book, or item to lend.',
    2: 'Confirming item availability, condition, and pickup arrangements over chat.',
    3: 'Quick doorstep or public exchange of borrowed item for short-term use.',
    4: 'Ongoing neighborhood item-sharing library or tool swap network member.',
    5: 'High-value equipment sharing (camera gear, camping equipment) with verification.',
  },
  'Volunteer & Community Action': {
    1: 'Inquiring about local community volunteer opportunities or civic causes.',
    2: 'Virtual coordination call for an upcoming community initiative.',
    3: 'Participating together in a 2-hour park cleanup, food drive, or community garden shift.',
    4: 'Regular weekend volunteering lead for local social impact projects.',
    5: 'Community action group founder or crisis neighborhood relief organizer.',
  },
  'Arts & Craft Partner': {
    1: 'Sharing artwork photos, craft material tips, or gallery recommendations.',
    2: 'Virtual art critique or collaborative digital canvas sketching session.',
    3: 'Outdoor photo walk, museum sketching session, or pottery studio visit.',
    4: 'Weekly craft workshop or joint art gallery exhibition attendance.',
    5: 'Collaborative art installation creation or co-exhibiting creative works.',
  },
  'City Exploration & Walking Group': {
    1: 'Asking about scenic walking routes or historic walking paths nearby.',
    2: 'Planning a 5km walking route and setting a meeting point.',
    3: 'Casual evening walk or weekend morning stroll with a local peer.',
    4: 'Regular neighborhood walking club or urban exploration group member.',
    5: 'Night-walk community scenic tour host & local heritage explorer.',
  },
};

// Aliases mapping for short category names
const ALIAS_MAP: Record<string, string> = {
  'Medical': 'Medical Emergency',
  'Security': 'Security & Assault',
  'Fire & Hazard': 'Fire & Explosion',
  'Transport': 'Transport & Evacuation',
  'Disaster': 'Disaster & Flood',
  'Women Safety': 'Women Safety & Harassment',
  'Child Care': 'Child Emergency & Lost',
  'Accident': 'Accident & Collision',
  'Animal Rescue': 'Animal Rescue & Hazard',
  'Senior Assist': 'Senior Citizen Assist',
  'Blackout': 'Power Grid & Blackout',
  'Coffee': 'Coffee & Social Chat',
  'Study': 'Study & Homework Buddy',
  'Sports': 'Sports & Workout Partner',
  'Travel': 'Travel & Sightseeing Companion',
  'Language': 'Language Exchange & Practice',
  'Skill Swap': 'Skill Swap & Mentorship',
  'Gaming': 'Hobby & Gaming Pair',
  'Co-Working': 'Co-Working & Professional Network',
  'Event Buddy': 'Event & Concert Buddy',
  'Local Guide': 'Neighborhood Advice & Local Guide',
  'Pet Meetup': 'Pet Playdate & Walking',
  'Foodie': 'Foodie & Culinary Meetup',
  'Book Club': 'Book & Film Discussion',
  'Music Jam': 'Music Jamming & Creative',
  'Carpool': 'Carpool & Commute Partner',
  'Tech Collab': 'Tech & Coding Collaboration',
  'Item Share': 'Item Sharing & Borrowing',
  'Volunteer': 'Volunteer & Community Action',
  'Art Partner': 'Arts & Craft Partner',
  'Walking Group': 'City Exploration & Walking Group',
};

/**
 * Returns a tailored context sentence based on category and urgency level (1-5).
 */
export function getCategoryUrgencyContext(category?: CategoryType | string | null, urgency: number = 3): string {
  const normalizedLevel = Math.max(1, Math.min(5, Math.round(urgency))) as UrgencyLevel;
  const targetCategory = (category && ALIAS_MAP[category]) || category || 'General Request';
  const categoryMap = CATEGORY_URGENCY_CONTEXTS[targetCategory] || CATEGORY_URGENCY_CONTEXTS['General Request'];
  return categoryMap[normalizedLevel] || categoryMap[3];
}
